general:
  cpiApiServiceKeyCredentialsId: 'integrationsuitekey'
  integrationFlowId: 'Receive_SuccessFactors_Platform_Event'
stages:
  Upload:
    enabled: true
  Deploy:
    enabled: false
  Integration Test:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "CICDTesting"
    integrationFlowName: 'IS_Receive_SF_Platform_Event_COPY'
  integrationArtifactUpdateConfiguration:
    integrationFlowVersion: '1.0.0'
    parameterKey: 'My_Config_Param'
    parameterValue: 'CI_CD'
